### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by fffddddd** [kangmintong/DiffAttack#2]
When I want to use the unet model, it needs to load 'pretrained/ckpt.pt'. But I cannot find it. Could you give me the link?

**Comment by kangmintong** [comment]
Please refer to this link to download it: https://drive.google.com/file/d/1iWHGBBXix2uzoZ4zNYvu_5q91pymAkez/view?usp=sharing
Thanks!

**Comment by fffddddd** [comment]
OK. Thank you!
